### ISSUE TITLE
*-not-* variants generate wrong selector

### ISSUE THREAD

**Issue by apollo79** [zirbest/unocss-preset-primitives#17]
When using the class `ui-not-invalid:bg-red` for example the following css is generated:
```css
.ui-not-invalid\:bg-red[data]:not([data-invalid]),
:where([data]:not([data-invalid])) .ui-not-invalid\:bg-red:not(data) {
  --un-bg-opacity:1;
  background-color:rgb(248 113 113 / var(--un-bg-opacity));
}
```

For `ui-not-selected:bg-red` it looks like this:
```css
.ui-not-selected\:bg-red[data]:not([data-selected]),
:where([data]:not([data-selected])) .ui-not-selected\:bg-red:not(data) {
  --un-bg-opacity:1;
  background-color:rgb(248 113 113 / var(--un-bg-opacity));
}
```
These selectors use `[data]` in some places, which does not select the correct element.
